apiVersion: v1
data:
  DB_USERNAME: {{ .Values.mysql.DB_USERNAME }}
  DB_PASSWORD: {{ .Values.mysql.DB_PASSWORD }}
kind: Secret
metadata:
  name: {{ .Values.mysql.config.name }}-secret
  namespace: {{ .Release.Namespace }}

