apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Chart.Name }}-ingress
    alb.ingress.kubernetes.io/security-groups: {{ .Values.ingress.security.groups }}
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ .Values.services.demo.name }}
            port:
              number: {{ .Values.services.demo.port }}
        path: {{ .Values.services.demo.path }}
        pathType: Prefix
